### DO NOT EDIT THIS FILE ###
### This file was automatically generated and changes will be lost!
### To make changes, edit aperturectl.rb.template instead.

# vim: ft=ruby
# Documentation: https://docs.brew.sh/Formula-Cookbook
#                https://rubydoc.brew.sh/Formula
class Aperturectl < Formula
  desc "CLI for flow control and reliability management for modern web applications"
  homepage "https://www.fluxninja.com"
  url "https://api.github.com/repos/fluxninja/aperture/tarball/v0.22.0-rc.1"
  version "0.22.0-rc.1"
  sha256 "20890f3ad84ece9b64cd9c2e382678a9bbe352bc40cca4d5029efb3d0536ac73"
  license "Apache-2.0"

  depends_on "go" => :build

  def install
    ENV["GIT_BRANCH"]="main"
    ENV["GIT_COMMIT_HASH"]="5d995315f54de420645c457676ab8ba7a2b1e518"
    ENV["SOURCE"]="./cmd/aperturectl"
    ENV["TARGET"]=bin/name
    ENV["VERSION"]=version
    ENV["PREFIX"]="aperture"
    ENV["LDFLAGS"]="-s -w"
    system "./pkg/info/build.sh"

    generate_completions_from_executable(bin/name, "completion")
  end

  test do
    # `test do` will create, run in and delete a temporary directory.
    #
    # The installed folder is not in the path, so use the entire path to any
    # executables being tested: `system "#{bin}/program", "do", "something"`.
    assert_match "aperturectl version #{version.to_s}", shell_output("#{bin}/aperturectl --version")
  end
end
