name: brew pr-pull
on:
  workflow_dispatch:
    inputs:
      pull_request_number:
        description: 'Pull request number'
        required: true
        type: number
      pull_request_branch:
        description: 'Pull request branch'
        required: true
        type: string

concurrency:
  cancel-in-progress: true
  group: ${{ github.repository }}-update-brew-pr-pull

jobs:
  pr-pull:
    runs-on: ubuntu-22.04
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Set up git
        uses: Homebrew/actions/git-user-config@master

      - name: Pull bottles
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ github.token }}
          HOMEBREW_GITHUB_PACKAGES_TOKEN: ${{ github.token }}
          HOMEBREW_GITHUB_PACKAGES_USER: ${{ github.actor }}
          PULL_REQUEST: ${{ inputs.pull_request_number }}
        run: brew pr-pull --debug --tap=$GITHUB_REPOSITORY $PULL_REQUEST

      - name: Push commits
        uses: Homebrew/actions/git-try-push@master
        with:
          token: ${{ github.token }}
          branch: main

      - name: Delete branch
        if: inputs.pull_request_branch != ''
        env:
          BRANCH: ${{ inputs.pull_request_branch }}
        run: git push --delete origin $BRANCH
